INSERT INTO characters VALUES(0,'Regulus Arcturus Black','Brother of Sirius. Used to be a Death Eater but defected.');
INSERT INTO characters VALUES(1,'Sirius Black','Best friend of James Potter and godfather of Harry.');
INSERT INTO characters VALUES(2,'Lavender Brown','Killed by a werewolf. She was a gryffindor student who dated Ron. ');
INSERT INTO characters VALUES(3,'Cho Chang','Ravenclaw student who dated Cedric Diggory and Harry Potter.');
INSERT INTO characters VALUES(4,'Vincent Crabbe Sr.','Father of Crabbe and death-eater who escaped Azkaban.');
INSERT INTO characters VALUES(5,'Vincent Crabbe','Slytherin student who was best friends with Goyle and followed Draco.');
INSERT INTO characters VALUES(6,'Bartemius "Barty" Crouch Sr.','Head of the department of Internation Magical Cooperation. Killed by his son.');
INSERT INTO characters VALUES(7,'Bartemius "Barty" Crouch Jr.','Death Eater who impersonated Alastor Moody.');
INSERT INTO characters VALUES(8,'Fleur Delacour','Participated in the Triwizard tournament and married Bill Weasley.');
INSERT INTO characters VALUES(9,'Cedric Diggory','Participated in the Triwizard tournament and got killed by Voldemort.');
INSERT INTO characters VALUES(10,'Alberforth Dumbledore','Albus'' brother and owner of Hog''s Head.');
INSERT INTO characters VALUES(11,'Albus Dumbledore','Headmaster of Hogwards killed by Snape.');
INSERT INTO characters VALUES(12,'Dudley Dursley','Muggle son of Vernon and Petunia and first-cousin of Harry.');
INSERT INTO characters VALUES(13,'Petunia Dursley','Harry''s aunt and sister of Lily.');
INSERT INTO characters VALUES(14,'Vernon Dursley','Harry''s muggle uncle.');
INSERT INTO characters VALUES(15,'Argus Filch','Squib caretake of Hogwards.');
INSERT INTO characters VALUES(16,'Seamus Finnigan','Harry''s friend and member of Dumbledore''s army.');
INSERT INTO characters VALUES(17,'Nicolas Flamel','Creator of the Philosopher''s Stone.');
INSERT INTO characters VALUES(18,'Cornelius Fudge','Minister of Magic that was forced to resign.');
INSERT INTO characters VALUES(19,'Goyle Sr.','Death Eater and father of Gregory Goyle.');
INSERT INTO characters VALUES(20,'Gregory Goyle','Best friend of Crabbe. Slytherin student and dies by falling into Fiendfyre.');
INSERT INTO characters VALUES(21,'Hermione Granger','One of Harry''s best friend and marries Ron Weasley.');
INSERT INTO characters VALUES(22,'Rubeus Hagrid','Half-giant who loves Harry. He was the keeper of Keys and Grounds at Hogwards.');
INSERT INTO characters VALUES(23,'Igor Karkaroff','Highmaster of Durmstrang and reformed death-eater.');
INSERT INTO characters VALUES(24,'Viktor Krum','Participant in the Triwizard tournament. Dated Hermione.');
INSERT INTO characters VALUES(25,'Bellatrix Lestrange','Death Eater who was killed by Molly Weasley.');
INSERT INTO characters VALUES(26,'Alice Longbottom','Mother of Neville who was tortured by Bellatrix.');
INSERT INTO characters VALUES(27,'Frank Longbottom','Father of Neville who was tortured by Bellatrix.');
INSERT INTO characters VALUES(28,'Neville Longbottom','Gryffindor student who was a member of Dumbledore''s army.');
INSERT INTO characters VALUES(29,'Luna Lovegood','Ravenclaw student who was a member of Dumbledore''s army.');
INSERT INTO characters VALUES(30,'Xenophilius Lovegood','Father of Luna and editor of The Quibbler.');
INSERT INTO characters VALUES(31,'Remus Lupin','Friend of James Potter and werewolf. He married Nymphadora.');
INSERT INTO characters VALUES(32,'Draco Malfoy','Slytherin student who had many arguments with Harry.');
INSERT INTO characters VALUES(33,'Lucius Malfoy','Father of Draco and influential Death-Eater.');
INSERT INTO characters VALUES(34,'Narcissa Malfoy','Mother of Draco and sister of Bellatrix.');
INSERT INTO characters VALUES(35,'Olympe Maxime','Half-giantess and headmistress of Beauxbatons.');
INSERT INTO characters VALUES(36,'Minerva McGonagall','Professor of Transfiguration and head of Gryffindor.');
INSERT INTO characters VALUES(37,'Alastor "Mad-Eye" Moody','Retired auror and member of the order of the Phoenix. Killed by Voldemort.');
INSERT INTO characters VALUES(38,'Peter Pettigrew','Betrays James and Lily Potter. Follower of Voldemort.');
INSERT INTO characters VALUES(39,'Harry Potter','The boy who lived. Main character of the series.');
INSERT INTO characters VALUES(40,'James Potter','Father of Harry. Murdered by Voldemort.');
INSERT INTO characters VALUES(41,'Lily Potter','Mother of Harry. Murdered by Voldemort.');
INSERT INTO characters VALUES(42,'Quirinus Quirrell','Possessed by Voldemort. Defence against the Dark Arts professor.');
INSERT INTO characters VALUES(43,'Tom Riddle Sr.','Muggle father of Voldemort who was killed by him.');
INSERT INTO characters VALUES(44,'Mary Riddle','Muggle mother of Voldemort who was killed by him.');
INSERT INTO characters VALUES(45,'Lord Voldemort','The antagonist of the series who murdered many.');
INSERT INTO characters VALUES(46,'Rita Skeeter','Reporter at the Daily Prophet.');
INSERT INTO characters VALUES(47,'Severus Snape','Head of the Slytherin house and saved Harry in many occasions.');
INSERT INTO characters VALUES(48,'Nymphadora Tonks','Married Remus Lupin and was killed by Bellatrix.');
INSERT INTO characters VALUES(49,'Dolores Janes Umbridge','Senior undersecretary to the Ministry of Magic. Eventually sent to Azkaban.');
INSERT INTO characters VALUES(50,'Arthur Weasley','Father of the Weasleys and member of the Order of the Phoenix.');
INSERT INTO characters VALUES(51,'Bill Weasley','Oldest son of Arthur and Molly. Husband of Fleur. ');
INSERT INTO characters VALUES(52,'Charlie Weasley','Second son of Arthur and Molly. Works with dragons in Romania.');
INSERT INTO characters VALUES(53,'Fred Weasley','Identical twin with George and co-owner of Weasleys'' Wizard Wheezes');
INSERT INTO characters VALUES(54,'George Weasley','Identical twin with Fred and co-owner of Weasleys'' Wizard Wheezes');
INSERT INTO characters VALUES(55,'Ginny Weasley','Marries Harry Potter and only daughter of Molly and Arthur.');
INSERT INTO characters VALUES(56,'Molly Weasley','Wife of Arthur and mother of the Weasleys. Kills Bellatrix.');
INSERT INTO characters VALUES(57,'Percy Weasley','Third son of Arthur and Molly. He is a Gryffindor prefect.');
INSERT INTO characters VALUES(58,'Ron Weasley','Harry''s best friend. Marries Hermione.');
INSERT INTO characters VALUES(59,'Dobby','House elf and friend of Harry. He is killed by Bellatrix.');
INSERT INTO characters VALUES(60,'Fluffy','Three-headed dog belonging to Rubeus Hagrid.');
INSERT INTO characters VALUES(61,'Hedwig','Harry''s owl.');
INSERT INTO characters VALUES(62,'Moaning Myrtle','Ghost at Hogwards.');
INSERT INTO characters VALUES(63,'Aragog','Acromantula belonging to Rubeus Hagrid.');
INSERT INTO characters VALUES(64,'Grawp','Giant-half brother of Hagrid.');

INSERT INTO relations VALUES(0,1,'-');
INSERT INTO relations VALUES(0,25,'-');
INSERT INTO relations VALUES(0,45,'-');
INSERT INTO relations VALUES(1,0,'-');
INSERT INTO relations VALUES(1,11,'+');
INSERT INTO relations VALUES(1,21,'+');
INSERT INTO relations VALUES(1,25,'-');
INSERT INTO relations VALUES(1,31,'+');
INSERT INTO relations VALUES(1,33,'-');
INSERT INTO relations VALUES(1,34,'-');
INSERT INTO relations VALUES(1,36,'+');
INSERT INTO relations VALUES(1,37,'+');
INSERT INTO relations VALUES(1,38,'-');
INSERT INTO relations VALUES(1,39,'+');
INSERT INTO relations VALUES(1,40,'+');
INSERT INTO relations VALUES(1,41,'+');
INSERT INTO relations VALUES(1,45,'-');
INSERT INTO relations VALUES(1,47,'-');
INSERT INTO relations VALUES(1,48,'+');
INSERT INTO relations VALUES(1,50,'+');
INSERT INTO relations VALUES(1,53,'+');
INSERT INTO relations VALUES(1,54,'+');
INSERT INTO relations VALUES(1,55,'+');
INSERT INTO relations VALUES(1,58,'+');
INSERT INTO relations VALUES(2,21,'-');
INSERT INTO relations VALUES(2,28,'+');
INSERT INTO relations VALUES(2,58,'+');
INSERT INTO relations VALUES(3,9,'+');
INSERT INTO relations VALUES(3,16,'+');
INSERT INTO relations VALUES(3,21,'+');
INSERT INTO relations VALUES(3,28,'+');
INSERT INTO relations VALUES(3,39,'+');
INSERT INTO relations VALUES(3,45,'-');
INSERT INTO relations VALUES(3,58,'+');
INSERT INTO relations VALUES(4,0,'+');
INSERT INTO relations VALUES(4,5,'+');
INSERT INTO relations VALUES(4,6,'+');
INSERT INTO relations VALUES(4,25,'+');
INSERT INTO relations VALUES(4,33,'+');
INSERT INTO relations VALUES(4,38,'+');
INSERT INTO relations VALUES(4,45,'+');
INSERT INTO relations VALUES(4,47,'+');
INSERT INTO relations VALUES(5,4,'+');
INSERT INTO relations VALUES(5,49,'+');
INSERT INTO relations VALUES(5,20,'+');
INSERT INTO relations VALUES(5,21,'-');
INSERT INTO relations VALUES(5,32,'+');
INSERT INTO relations VALUES(5,39,'-');
INSERT INTO relations VALUES(5,58,'-');
INSERT INTO relations VALUES(6,4,'+');
INSERT INTO relations VALUES(6,7,'-');
INSERT INTO relations VALUES(6,23,'+');
INSERT INTO relations VALUES(6,57,'+');
INSERT INTO relations VALUES(7,6,'-');
INSERT INTO relations VALUES(7,21,'-');
INSERT INTO relations VALUES(7,28,'+');
INSERT INTO relations VALUES(7,36,'-');
INSERT INTO relations VALUES(7,37,'-');
INSERT INTO relations VALUES(7,39,'-');
INSERT INTO relations VALUES(7,45,'+');
INSERT INTO relations VALUES(7,47,'-');
INSERT INTO relations VALUES(7,38,'+');
INSERT INTO relations VALUES(8,21,'+');
INSERT INTO relations VALUES(8,25,'-');
INSERT INTO relations VALUES(8,28,'+');
INSERT INTO relations VALUES(8,37,'+');
INSERT INTO relations VALUES(8,39,'+');
INSERT INTO relations VALUES(8,51,'+');
INSERT INTO relations VALUES(8,55,'+');
INSERT INTO relations VALUES(8,56,'+');
INSERT INTO relations VALUES(8,58,'+');
INSERT INTO relations VALUES(9,3,'+');
INSERT INTO relations VALUES(9,39,'+');
INSERT INTO relations VALUES(9,45,'-');
INSERT INTO relations VALUES(10,11,'+');
INSERT INTO relations VALUES(10,21,'+');
INSERT INTO relations VALUES(10,39,'+');
INSERT INTO relations VALUES(10,58,'+');
INSERT INTO relations VALUES(10,59,'+');
INSERT INTO relations VALUES(11,1,'+');
INSERT INTO relations VALUES(11,10,'+');
INSERT INTO relations VALUES(11,13,'-');
INSERT INTO relations VALUES(11,14,'-');
INSERT INTO relations VALUES(11,21,'+');
INSERT INTO relations VALUES(11,22,'+');
INSERT INTO relations VALUES(11,25,'-');
INSERT INTO relations VALUES(11,31,'+');
INSERT INTO relations VALUES(11,36,'+');
INSERT INTO relations VALUES(11,36,'+');
INSERT INTO relations VALUES(11,37,'+');
INSERT INTO relations VALUES(11,38,'-');
INSERT INTO relations VALUES(11,39,'+');
INSERT INTO relations VALUES(11,40,'+');
INSERT INTO relations VALUES(11,41,'+');
INSERT INTO relations VALUES(11,42,'-');
INSERT INTO relations VALUES(11,45,'-');
INSERT INTO relations VALUES(11,46,'-');
INSERT INTO relations VALUES(11,47,'+');
INSERT INTO relations VALUES(11,49,'-');
INSERT INTO relations VALUES(11,49,'-');
INSERT INTO relations VALUES(11,50,'+');
INSERT INTO relations VALUES(11,51,'+');
INSERT INTO relations VALUES(11,52,'+');
INSERT INTO relations VALUES(11,53,'+');
INSERT INTO relations VALUES(11,54,'+');
INSERT INTO relations VALUES(11,55,'+');
INSERT INTO relations VALUES(11,56,'+');
INSERT INTO relations VALUES(11,57,'+');
INSERT INTO relations VALUES(11,58,'+');
INSERT INTO relations VALUES(12,12,'+');
INSERT INTO relations VALUES(12,14,'+');
INSERT INTO relations VALUES(12,39,'-');
INSERT INTO relations VALUES(12,22,'-');
INSERT INTO relations VALUES(13,11,'-');
INSERT INTO relations VALUES(13,12,'+');
INSERT INTO relations VALUES(13,13,'+');
INSERT INTO relations VALUES(13,39,'-');
INSERT INTO relations VALUES(13,41,'-');
INSERT INTO relations VALUES(14,11,'-');
INSERT INTO relations VALUES(14,12,'+');
INSERT INTO relations VALUES(14,13,'+');
INSERT INTO relations VALUES(14,39,'-');
INSERT INTO relations VALUES(15,1,'-');
INSERT INTO relations VALUES(15,11,'+');
INSERT INTO relations VALUES(15,22,'-');
INSERT INTO relations VALUES(15,36,'-');
INSERT INTO relations VALUES(15,38,'-');
INSERT INTO relations VALUES(15,39,'-');
INSERT INTO relations VALUES(15,40,'-');
INSERT INTO relations VALUES(15,47,'+');
INSERT INTO relations VALUES(15,49,'+');
INSERT INTO relations VALUES(15,53,'-');
INSERT INTO relations VALUES(15,54,'-');
INSERT INTO relations VALUES(16,2,'+');
INSERT INTO relations VALUES(16,3,'+');
INSERT INTO relations VALUES(16,21,'+');
INSERT INTO relations VALUES(16,28,'+');
INSERT INTO relations VALUES(16,29,'+');
INSERT INTO relations VALUES(16,39,'+');
INSERT INTO relations VALUES(16,55,'+');
INSERT INTO relations VALUES(16,58,'+');
INSERT INTO relations VALUES(17,11,'+');
INSERT INTO relations VALUES(18,11,'-');
INSERT INTO relations VALUES(18,33,'+');
INSERT INTO relations VALUES(18,39,'-');
INSERT INTO relations VALUES(18,49,'+');
INSERT INTO relations VALUES(18,50,'-');
INSERT INTO relations VALUES(18,57,'+');
INSERT INTO relations VALUES(19,4,'+');
INSERT INTO relations VALUES(19,20,'+');
INSERT INTO relations VALUES(19,45,'+');
INSERT INTO relations VALUES(20,19,'+');
INSERT INTO relations VALUES(20,5,'+');
INSERT INTO relations VALUES(20,32,'+');
INSERT INTO relations VALUES(20,39,'-');
INSERT INTO relations VALUES(20,45,'+');
INSERT INTO relations VALUES(21,39,'+');
INSERT INTO relations VALUES(21,58,'+');
INSERT INTO relations VALUES(21,54,'+');
INSERT INTO relations VALUES(21,56,'+');
INSERT INTO relations VALUES(21,47,'+');
INSERT INTO relations VALUES(21,29,'+');
INSERT INTO relations VALUES(21,28,'+');
INSERT INTO relations VALUES(21,45,'-');
INSERT INTO relations VALUES(21,38,'-');
INSERT INTO relations VALUES(21,32,'-');
INSERT INTO relations VALUES(21,15,'-');
INSERT INTO relations VALUES(21,20,'-');
INSERT INTO relations VALUES(22,45,'-');
INSERT INTO relations VALUES(22,60,'+');
INSERT INTO relations VALUES(22,63,'+');
INSERT INTO relations VALUES(22,64,'+');
INSERT INTO relations VALUES(22,58,'+');
INSERT INTO relations VALUES(22,21,'+');
INSERT INTO relations VALUES(22,47,'+');
INSERT INTO relations VALUES(22,39,'+');
INSERT INTO relations VALUES(22,28,'+');
INSERT INTO relations VALUES(22,35,'+');
INSERT INTO relations VALUES(22,36,'+');
INSERT INTO relations VALUES(22,11,'+');
INSERT INTO relations VALUES(23,45,'-');
INSERT INTO relations VALUES(23,24,'+');
INSERT INTO relations VALUES(24,23,'+');
INSERT INTO relations VALUES(24,39,'+');
INSERT INTO relations VALUES(24,8,'+');
INSERT INTO relations VALUES(24,9,'+');
INSERT INTO relations VALUES(24,21,'+');
INSERT INTO relations VALUES(25,45,'+');
INSERT INTO relations VALUES(25,33,'+');
INSERT INTO relations VALUES(25,34,'+');
INSERT INTO relations VALUES(25,1,'-');
INSERT INTO relations VALUES(25,39,'-');
INSERT INTO relations VALUES(25,48,'-');
INSERT INTO relations VALUES(25,56,'-');
INSERT INTO relations VALUES(25,59,'-');
INSERT INTO relations VALUES(26,27,'+');
INSERT INTO relations VALUES(26,27,'+');
INSERT INTO relations VALUES(26,28,'+');
INSERT INTO relations VALUES(27,26,'+');
INSERT INTO relations VALUES(27,45,'-');
INSERT INTO relations VALUES(27,28,'+');
INSERT INTO relations VALUES(28,39,'+');
INSERT INTO relations VALUES(28,45,'-');
INSERT INTO relations VALUES(28,21,'+');
INSERT INTO relations VALUES(28,58,'+');
INSERT INTO relations VALUES(28,29,'+');
INSERT INTO relations VALUES(28,32,'-');
INSERT INTO relations VALUES(29,28,'+');
INSERT INTO relations VALUES(29,39,'+');
INSERT INTO relations VALUES(29,21,'+');
INSERT INTO relations VALUES(29,58,'+');
INSERT INTO relations VALUES(30,29,'+');
INSERT INTO relations VALUES(31,38,'-');
INSERT INTO relations VALUES(31,45,'-');
INSERT INTO relations VALUES(31,40,'+');
INSERT INTO relations VALUES(31,1,'+');
INSERT INTO relations VALUES(31,48,'+');
INSERT INTO relations VALUES(31,39,'+');
INSERT INTO relations VALUES(31,36,'+');
INSERT INTO relations VALUES(32,5,'+');
INSERT INTO relations VALUES(32,20,'+');
INSERT INTO relations VALUES(32,33,'+');
INSERT INTO relations VALUES(32,34,'+');
INSERT INTO relations VALUES(32,39,'-');
INSERT INTO relations VALUES(32,21,'-');
INSERT INTO relations VALUES(32,58,'-');
INSERT INTO relations VALUES(33,32,'+');
INSERT INTO relations VALUES(33,34,'+');
INSERT INTO relations VALUES(33,45,'+');
INSERT INTO relations VALUES(33,39,'-');
INSERT INTO relations VALUES(33,59,'-');
INSERT INTO relations VALUES(34,33,'+');
INSERT INTO relations VALUES(34,45,'+');
INSERT INTO relations VALUES(34,25,'+');
INSERT INTO relations VALUES(35,22,'+');
INSERT INTO relations VALUES(35,8,'+');
INSERT INTO relations VALUES(35,11,'+');
INSERT INTO relations VALUES(35,23,'+');
INSERT INTO relations VALUES(36,15,'+');
INSERT INTO relations VALUES(36,22,'+');
INSERT INTO relations VALUES(36,49,'-');
INSERT INTO relations VALUES(36,45,'-');
INSERT INTO relations VALUES(36,11,'+');
INSERT INTO relations VALUES(36,39,'+');
INSERT INTO relations VALUES(39,36,'+');
INSERT INTO relations VALUES(36,21,'+');
INSERT INTO relations VALUES(21,36,'+');
INSERT INTO relations VALUES(36,58,'+');
INSERT INTO relations VALUES(58,36,'+');
INSERT INTO relations VALUES(36,45,'-');
INSERT INTO relations VALUES(45,36,'-');
INSERT INTO relations VALUES(36,11,'+');
INSERT INTO relations VALUES(11,36,'+');
INSERT INTO relations VALUES(37,39,'+');
INSERT INTO relations VALUES(37,50,'+');
INSERT INTO relations VALUES(37,56,'+');
INSERT INTO relations VALUES(39,37,'+');
INSERT INTO relations VALUES(39,45,'-');
INSERT INTO relations VALUES(37,21,'+');
INSERT INTO relations VALUES(21,37,'+');
INSERT INTO relations VALUES(37,21,'+');
INSERT INTO relations VALUES(21,37,'+');
INSERT INTO relations VALUES(37,7,'-');
INSERT INTO relations VALUES(7,37,'-');
INSERT INTO relations VALUES(37,11,'+');
INSERT INTO relations VALUES(11,37,'+');
INSERT INTO relations VALUES(37,45,'-');
INSERT INTO relations VALUES(45,37,'-');
INSERT INTO relations VALUES(38,1,'-');
INSERT INTO relations VALUES(1,38,'-');
INSERT INTO relations VALUES(38,40,'-');
INSERT INTO relations VALUES(40,38,'-');
INSERT INTO relations VALUES(38,41,'-');
INSERT INTO relations VALUES(41,38,'-');
INSERT INTO relations VALUES(41,39,'+');
INSERT INTO relations VALUES(38,45,'+');
INSERT INTO relations VALUES(45,38,'+');
INSERT INTO relations VALUES(38,39,'-');
INSERT INTO relations VALUES(39,38,'-');
INSERT INTO relations VALUES(40,39,'+');
INSERT INTO relations VALUES(39,40,'+');
INSERT INTO relations VALUES(40,31,'+');
INSERT INTO relations VALUES(31,40,'+');
INSERT INTO relations VALUES(40,1,'+');
INSERT INTO relations VALUES(1,40,'+');
INSERT INTO relations VALUES(40,38,'-');
INSERT INTO relations VALUES(38,40,'-');
INSERT INTO relations VALUES(40,45,'-');
INSERT INTO relations VALUES(45,40,'-');
INSERT INTO relations VALUES(40,41,'+');
INSERT INTO relations VALUES(41,40,'+');
INSERT INTO relations VALUES(41,45,'-');
INSERT INTO relations VALUES(45,41,'-');
INSERT INTO relations VALUES(41,47,'+');
INSERT INTO relations VALUES(47,41,'+');
INSERT INTO relations VALUES(42,39,'-');
INSERT INTO relations VALUES(39,42,'-');
INSERT INTO relations VALUES(42,21,'-');
INSERT INTO relations VALUES(21,42,'-');
INSERT INTO relations VALUES(42,21,'-');
INSERT INTO relations VALUES(21,42,'-');
INSERT INTO relations VALUES(42,11,'-');
INSERT INTO relations VALUES(11,42,'-');
INSERT INTO relations VALUES(42,45,'-');
INSERT INTO relations VALUES(45,42,'-');
INSERT INTO relations VALUES(43,45,'-');
INSERT INTO relations VALUES(43,43,'-');
INSERT INTO relations VALUES(43,44,'+');
INSERT INTO relations VALUES(44,43,'+');
INSERT INTO relations VALUES(44,45,'-');
INSERT INTO relations VALUES(43,45,'-');
INSERT INTO relations VALUES(45,43,'-');
INSERT INTO relations VALUES(46,39,'-');
INSERT INTO relations VALUES(39,46,'-');
INSERT INTO relations VALUES(46,11,'-');
INSERT INTO relations VALUES(11,46,'-');
INSERT INTO relations VALUES(47,39,'+');
INSERT INTO relations VALUES(39,47,'+');
INSERT INTO relations VALUES(47,21,'+');
INSERT INTO relations VALUES(21,47,'+');
INSERT INTO relations VALUES(47,21,'+');
INSERT INTO relations VALUES(21,47,'+');
INSERT INTO relations VALUES(42,11,'+');
INSERT INTO relations VALUES(11,42,'+');
INSERT INTO relations VALUES(47,41,'+');
INSERT INTO relations VALUES(41,47,'+');
INSERT INTO relations VALUES(47,45,'-');
INSERT INTO relations VALUES(45,47,'-');
INSERT INTO relations VALUES(48,31,'+');
INSERT INTO relations VALUES(48,45,'-');
INSERT INTO relations VALUES(31,48,'+');
INSERT INTO relations VALUES(49,39,'-');
INSERT INTO relations VALUES(39,49,'-');
INSERT INTO relations VALUES(49,21,'-');
INSERT INTO relations VALUES(21,49,'-');
INSERT INTO relations VALUES(49,21,'-');
INSERT INTO relations VALUES(21,49,'-');
INSERT INTO relations VALUES(49,11,'-');
INSERT INTO relations VALUES(11,49,'-');
INSERT INTO relations VALUES(49,18,'+');
INSERT INTO relations VALUES(18,49,'+');
INSERT INTO relations VALUES(50,21,'+');
INSERT INTO relations VALUES(50,1,'+');
INSERT INTO relations VALUES(50,11,'+');
INSERT INTO relations VALUES(50,33,'-');
INSERT INTO relations VALUES(50,39,'+');
INSERT INTO relations VALUES(21,50,'+');
INSERT INTO relations VALUES(50,51,'+');
INSERT INTO relations VALUES(51,50,'+');
INSERT INTO relations VALUES(50,52,'+');
INSERT INTO relations VALUES(52,50,'+');
INSERT INTO relations VALUES(50,53,'+');
INSERT INTO relations VALUES(53,50,'+');
INSERT INTO relations VALUES(50,54,'+');
INSERT INTO relations VALUES(54,50,'+');
INSERT INTO relations VALUES(50,54,'+');
INSERT INTO relations VALUES(54,50,'+');
INSERT INTO relations VALUES(50,55,'+');
INSERT INTO relations VALUES(55,50,'+');
INSERT INTO relations VALUES(50,57,'+');
INSERT INTO relations VALUES(57,50,'+');
INSERT INTO relations VALUES(51,39,'+');
INSERT INTO relations VALUES(51,45,'-');
INSERT INTO relations VALUES(51,21,'+');
INSERT INTO relations VALUES(21,51,'+');
INSERT INTO relations VALUES(50,51,'+');
INSERT INTO relations VALUES(51,50,'+');
INSERT INTO relations VALUES(51,52,'+');
INSERT INTO relations VALUES(52,51,'+');
INSERT INTO relations VALUES(51,53,'+');
INSERT INTO relations VALUES(53,51,'+');
INSERT INTO relations VALUES(51,54,'+');
INSERT INTO relations VALUES(54,51,'+');
INSERT INTO relations VALUES(51,54,'+');
INSERT INTO relations VALUES(54,51,'+');
INSERT INTO relations VALUES(51,55,'+');
INSERT INTO relations VALUES(55,51,'+');
INSERT INTO relations VALUES(51,57,'+');
INSERT INTO relations VALUES(57,51,'+');
INSERT INTO relations VALUES(52,21,'+');
INSERT INTO relations VALUES(52,39,'+');
INSERT INTO relations VALUES(21,52,'+');
INSERT INTO relations VALUES(50,52,'+');
INSERT INTO relations VALUES(52,50,'+');
INSERT INTO relations VALUES(52,53,'+');
INSERT INTO relations VALUES(53,52,'+');
INSERT INTO relations VALUES(52,54,'+');
INSERT INTO relations VALUES(54,52,'+');
INSERT INTO relations VALUES(52,54,'+');
INSERT INTO relations VALUES(52,45,'-');
INSERT INTO relations VALUES(54,52,'+');
INSERT INTO relations VALUES(52,55,'+');
INSERT INTO relations VALUES(55,52,'+');
INSERT INTO relations VALUES(52,57,'+');
INSERT INTO relations VALUES(57,52,'+');
INSERT INTO relations VALUES(53,21,'+');
INSERT INTO relations VALUES(53,31,'+');
INSERT INTO relations VALUES(53,38,'-');
INSERT INTO relations VALUES(53,39,'+');
INSERT INTO relations VALUES(53,45,'-');
INSERT INTO relations VALUES(53,47,'+');
INSERT INTO relations VALUES(53,50,'+');
INSERT INTO relations VALUES(53,51,'+');
INSERT INTO relations VALUES(53,52,'+');
INSERT INTO relations VALUES(53,54,'+');
INSERT INTO relations VALUES(53,55,'+');
INSERT INTO relations VALUES(53,56,'+');
INSERT INTO relations VALUES(53,57,'+');
INSERT INTO relations VALUES(53,58,'+');
INSERT INTO relations VALUES(54,21,'+');
INSERT INTO relations VALUES(54,31,'+');
INSERT INTO relations VALUES(54,38,'-');
INSERT INTO relations VALUES(54,39,'+');
INSERT INTO relations VALUES(54,45,'-');
INSERT INTO relations VALUES(54,47,'+');
INSERT INTO relations VALUES(54,50,'+');
INSERT INTO relations VALUES(54,51,'+');
INSERT INTO relations VALUES(54,52,'+');
INSERT INTO relations VALUES(54,53,'+');
INSERT INTO relations VALUES(54,55,'+');
INSERT INTO relations VALUES(54,56,'+');
INSERT INTO relations VALUES(54,57,'+');
INSERT INTO relations VALUES(54,58,'+');
INSERT INTO relations VALUES(55,21,'+');
INSERT INTO relations VALUES(55,31,'+');
INSERT INTO relations VALUES(55,38,'-');
INSERT INTO relations VALUES(55,39,'+');
INSERT INTO relations VALUES(55,45,'-');
INSERT INTO relations VALUES(55,47,'+');
INSERT INTO relations VALUES(55,50,'+');
INSERT INTO relations VALUES(55,51,'+');
INSERT INTO relations VALUES(55,52,'+');
INSERT INTO relations VALUES(55,54,'+');
INSERT INTO relations VALUES(55,53,'+');
INSERT INTO relations VALUES(55,56,'+');
INSERT INTO relations VALUES(55,57,'+');
INSERT INTO relations VALUES(55,57,'+');
INSERT INTO relations VALUES(55,58,'+');
INSERT INTO relations VALUES(56,1,'+');
INSERT INTO relations VALUES(56,11,'+');
INSERT INTO relations VALUES(56,21,'+');
INSERT INTO relations VALUES(56,33,'-');
INSERT INTO relations VALUES(56,39,'+');
INSERT INTO relations VALUES(56,45,'-');
INSERT INTO relations VALUES(56,50,'+');
INSERT INTO relations VALUES(56,51,'+');
INSERT INTO relations VALUES(56,52,'+');
INSERT INTO relations VALUES(56,53,'+');
INSERT INTO relations VALUES(56,54,'+');
INSERT INTO relations VALUES(56,55,'+');
INSERT INTO relations VALUES(56,57,'+');
INSERT INTO relations VALUES(56,58,'+');
INSERT INTO relations VALUES(57,50,'+');
INSERT INTO relations VALUES(57,51,'+');
INSERT INTO relations VALUES(57,52,'+');
INSERT INTO relations VALUES(57,53,'+');
INSERT INTO relations VALUES(57,54,'+');
INSERT INTO relations VALUES(57,55,'+');
INSERT INTO relations VALUES(57,56,'+');
INSERT INTO relations VALUES(57,58,'+');
INSERT INTO relations VALUES(58,1,'+');
INSERT INTO relations VALUES(58,8,'+');
INSERT INTO relations VALUES(58,11,'+');
INSERT INTO relations VALUES(58,15,'-');
INSERT INTO relations VALUES(58,16,'+');
INSERT INTO relations VALUES(58,20,'-');
INSERT INTO relations VALUES(58,21,'+');
INSERT INTO relations VALUES(58,22,'+');
INSERT INTO relations VALUES(58,25,'-');
INSERT INTO relations VALUES(58,28,'+');
INSERT INTO relations VALUES(58,29,'+');
INSERT INTO relations VALUES(58,31,'+');
INSERT INTO relations VALUES(58,32,'-');
INSERT INTO relations VALUES(58,33,'-');
INSERT INTO relations VALUES(58,36,'+');
INSERT INTO relations VALUES(58,37,'+');
INSERT INTO relations VALUES(58,38,'-');
INSERT INTO relations VALUES(58,39,'+');
INSERT INTO relations VALUES(58,45,'-');
INSERT INTO relations VALUES(58,47,'+');
INSERT INTO relations VALUES(58,49,'-');
INSERT INTO relations VALUES(58,50,'+');
INSERT INTO relations VALUES(58,51,'+');
INSERT INTO relations VALUES(58,52,'+');
INSERT INTO relations VALUES(58,53,'+');
INSERT INTO relations VALUES(58,54,'+');
INSERT INTO relations VALUES(58,55,'+');
INSERT INTO relations VALUES(58,56,'+');
INSERT INTO relations VALUES(58,57,'+');
INSERT INTO relations VALUES(58,59,'+');
INSERT INTO relations VALUES(58,60,'-');
INSERT INTO relations VALUES(58,63,'-');
INSERT INTO relations VALUES(58,64,'+');
INSERT INTO relations VALUES(59,21,'+');
INSERT INTO relations VALUES(59,25,'-');
INSERT INTO relations VALUES(59,32,'-');
INSERT INTO relations VALUES(59,33,'-');
INSERT INTO relations VALUES(59,39,'+');
INSERT INTO relations VALUES(59,58,'+');
INSERT INTO relations VALUES(60,21,'-');
INSERT INTO relations VALUES(60,22,'+');
INSERT INTO relations VALUES(60,39,'-');
INSERT INTO relations VALUES(60,58,'-');
INSERT INTO relations VALUES(61,39,'+');
INSERT INTO relations VALUES(62,39,'+');
INSERT INTO relations VALUES(63,21,'-');
INSERT INTO relations VALUES(63,22,'+');
INSERT INTO relations VALUES(63,39,'-');
INSERT INTO relations VALUES(63,58,'-');
INSERT INTO relations VALUES(64,21,'+');
INSERT INTO relations VALUES(64,22,'+');
INSERT INTO relations VALUES(64,39,'+');
INSERT INTO relations VALUES(63,58,'+');
